---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.frontend.labels.app }}
  namespace: argocd
spec:
  destination:
    namespace: todo-list
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
    path: mongo
    repoURL: 'https://github.com/gitafolabi/argo'
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true