apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels: 
    group: {{ .Values.mongo.group }}
spec:
  type: {{ .Values.mongo.service.type }}
  selector:             
    app: {{ .Values.mongo.name }}
  ports:
    - port: {{ .Values.mongo.service.port }}       
      targetPort: {{ .Values.mongo.container.port }}   